# estou falando em quais maqunias vão ser instalados, onde estão as maquuinas no hosts.yml
# serguir nome no arquivo hosts
- hosts: apache-front 
#tudo que vem depois de tasks é terefa
  tasks:
  # estou passando o nome da tafera no a primeira tarefa
  - name: Instalando o apache
  # de apt: até o pkg: é a mesma coisa que apt-get install
    apt:
      pkg:
      # o install é no apache2
      - apache2
      # mesma coisa que apt-get update 
      update_cache: yes
    # nos tornamos o root, mesma coisa que dar um sudo alguma
    become: yes

  # aqu itemos uma segunda tarefa e o nome é Git clone
  - name: Git clone
  # chamando um pacotinho do ansible que cuida do Git
    ansible.builtin.git:
      # o repositório que vamos clonar
      repo: https://github.com/ibsonjunior/Mulher_Maravilha.git
      # onde vamos clonar
      dest: /home/ubuntu/Mulher_Maravilha/
      # qual é a branch que vamos clonar
      version: main
      # aqui estopu dizendo que quero seja feito update sempre que rodar a tarefa
      update: yes
      # force pq eu quero, baixa e pronto. eu mandei.
      force: yes


  # outraaaaa tafera agora pra copiaar com o nome de copiar pasta
  - name: copiar pasta
    #este atributo command: tu pode colocar qualquer comando que usaria na linha de comando, poderioa ping, cd 
    command: cp -rf /home/ubuntu/Mulher_Maravilha/. /var/www/html/
    # nos tornamos o root, mesma coisa que dar um sudo alguma
    become: yes




#nano playbook.yml
#pra caso queira fazer tudo pelo nano, vulgo notepad do terminal vuldo telinha preta


# comando para executar o ansible na maquina vulgo instancia EC2 de gerenciamento
#ansible-playbook playbook.yml -i hosts.yml -u ubuntu --private-key terraform-aws 